# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
    types:
      - closed


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: create pull request
      run: gh pr create -B base_branch -H branch_to_merge --repo efreymiller-r7/razor --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
      
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
